version: '3.9'
name: steam_app-dev
services:
  api:
    build: ./api
    command: "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    tty: true
    hostname: api
    container_name: api
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: 
      - ./.env.dev
    depends_on:
      - db
    # restart: always 

  redis:
    image: 'redis:alpine' 
    hostname: redis
    ports:
      - 6379:6379

  celery-worker:
      build: ./api
      command: "celery -A src.celery.worker.worker worker -l INFO -E"
      depends_on:
        - redis
        - db
      restart: on-failure
      env_file: 
        - ./.env.dev
      volumes:
      - ./api/:/usr/src/app/

  celery-beat:
      build: ./api
      command: "celery -A src.celery.worker.worker beat -l INFO"
      depends_on:
        - redis 
        - db
      restart: on-failure
      volumes:
        - ./api/:/usr/src/app/
      env_file: 
        - ./.env.dev

  flower:
    container_name: flower
    build: ./api
    command: celery -A src.celery.worker.worker flower --port=5555
    ports:
      - 5556:5555
    env_file: 
        - ./.env.dev
    depends_on:
      - api
      - redis
      - celery-worker
      - celery-beat
    
  # bot:
  #   build: ./bot
  #   command: "python main.py"
  #   tty: true
  #   volumes:
  #     - ./bot/:/usr/src/app/
  #   ports:
  #     - 2000:2000
  #   env_file: 
  #     - ./.env.dev

  # steam:
  #   build: ./steam
  #   command: "python main.py"
  #   tty: true
  #   volumes:
  #     - ./steam/:/usr/src/app/
  #   ports:
  #     - 4000:4000
  #   env_file: 
  #     - ./.env.dev
    
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  postgres_data:
